### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by piotrekkaminski** [colinmollenhour/Cm_Cache_Backend_File#26]
You are using each() in File.php:81 which is deprecated in PHP 7.2 and throws a warning. 
https://wiki.php.net/rfc/deprecations_php_7_2

Any chance you can update it?

**Comment by bbtimx** [comment]
Simply change to:

```
foreach ($options as $name => $value) {
    $this->setOption($name, $value);
}
```

**Comment by pmclain** [comment]
@colinmollenhour Any chance you could tag a new release including the two PHP 7.2 compatibility fixes? It would be greatly appreciated 😄

**Comment by colinmollenhour** [comment]
Sure, just tagged 1.4.1.
