### ISSUE TITLE
Extend the core instead of overwrite the core

### ISSUE THREAD

**Issue by goosehub** [colinmollenhour/Cm_Cache_Backend_File#27]
It seems like this module overwrites the core. I'm trying to avoid that so upgrading the core is simple, so it works with my build process, and the many other reasons altering the core is discouraged by the community.

In my attempt to refactor the module to extend, I see some things I didn't understand.

The module symlinks to `app/code/community/Cm/Cache/Backend/File.php`, but that file doesn't exist, although `app/code/community/Cm` exists.

`Cm_Cache_Backend_File` extends `Zend_Cache_Backend_File`, but `Zend_Cache_Backend_File` isn't currently a class in any Magento file.

The install instructions say change global/cache/backend to Cm_Cache_Backend_File, but I don't see "global/cache/backend" when I ctrl+f app/etc/local.xml. I don't even see "cache" when I ctrl+f.

Am I fundamentally misunderstanding how this module works? Have things changed in Magento 1.x that this module doesn't support? Any advice for my attempt to refactor this module?

I am currently on 1.9.2.4, and planning to upgrade soon to 1.9.3.3.

**Comment by goosehub** [comment]
I have figured what out is meant by editing the local.xml. I need to add the tags, not edit existing tags, so I added:

        <cache>
            <backend>Cm_Cache_Backend_File</backend>
        </cache>

I'm still trying to abstract this all out so it doesn't involve editing that file. I may post a fork if there's interest. Help on understanding the other two points still appreciated.

**Comment by colinmollenhour** [comment]
Hi Goose,  this isn't a traditional Magento "module", it is simply a PHP class that can be loaded by Magento's autoloader. The autoloader uses the "include_path" which is set in Mage.php during bootstrap so when Magento tries to instantiate `Cm_Cache_Backend_File` it will load `app/code/community/Cm/Cache/Backend/File.php`. That is really all there is to it.

**Comment by goosehub** [comment]
@colinmollenhour thanks that makes sense. Also, I figured out why my attempt to refactor into a module has not worked.

https://stackoverflow.com/questions/10014657/how-to-rewrite-the-magento-core-cache-model-mage-core-model-cache

It seems the cache functionality is declared is called before XMLs for the modules are loaded (more or less, I'm probably over simplifying it). Avoiding touching the core in this case might be not possible/practical. May or may not be worth noting this in the README as I know there's a lot of people that avoid touching the core.

Thanks for the script, looks promising for our use case.
