### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Cm_Cache_Backend_File' not found in C:\wamp\ www\gta\vendor\magento\zendframework1\library\Zend\Cache.php:153

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [colinmollenhour/Cm_Cache_Backend_File#29]
Anyone help me how can i solve below error while running the command : 

`C:\wamp\www\gta>php bin/magento setup:upgrade;

Fatal error: Uncaught Error: Class 'Cm_Cache_Backend_File' not found in C:\wamp\
www\gta\vendor\magento\zendframework1\library\Zend\Cache.php:153
Stack trace:
#0 C:\wamp\www\gta\vendor\magento\zendframework1\library\Zend\Cache.php(94): Zen
d_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)
#1 C:\wamp\www\gta\vendor\magento\framework\App\Cache\Frontend\Factory.php(155):
 Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array,
true, true, true)
#2 C:\wamp\www\gta\vendor\magento\framework\App\Cache\Frontend\Pool.php(67): Mag
ento\Framework\App\Cache\Frontend\Factory->create(Array)
#3 C:\wamp\www\gta\vendor\magento\framework\App\Cache\Frontend\Pool.php(146): Ma
gento\Framework\App\Cache\Frontend\Pool->_initialize()
#4 C:\wamp\www\gta\vendor\magento\framework\App\Cache\Type\FrontendPool.php(84):
 Magento\Framework\App\Cache\Frontend\Pool->get('default')
#5 C:\wamp\www\gta\vendor\magento\framework\App\Cache\Type\Config.php(49): Magen
to\Framework\App\Cache\Type\FrontendPool->get('config')
#6 C:\wamp\ in C:\wamp\www\gta\vendor\magento\zendframework1\library\Zend\Cache.
php on line 153

C:\wamp\www\gta>

`

**Comment by colinmollenhour** [comment]
It is assumed that your framework will auto-load the class. Alternatively you can `require` it explicitly in your bootstrap script.
