### ISSUE TITLE
getting issue for file permission

### ISSUE THREAD

**Issue by manishjaingit** [colinmollenhour/Cm_Cache_Backend_File#36]
https://github.com/colinmollenhour/Cm_Cache_Backend_File/blob/034bf73adfdc5b02057ae3ef2a2255b381f46944/File.php#L691

I am facing issue by running cron in Magento 2

In ErrorHandler.php line 61:

  Warning: file_put_contents(/data/html/var/cache//mage-tags/mage---935_CONFIG): failed to open stream: Permission denied in /data/html/vendor/colinmollenhour/cache-
  backend-file/File.php on line 691

can you please help me.

Thanks in advance.

**Comment by colinmollenhour** [comment]
The key part of the error message is "Permission denied" so you have a file permission issue. I.e., web server is unable to create/write files.
