### ISSUE TITLE
Update 1.4.6 sets unlimited lifetime to no cache

### ISSUE THREAD

**Issue by pcs-matze** [colinmollenhour/Cm_Cache_Backend_File#38]
Since Update 1.4.6 there is a change of caching behavior which has effects to Magento Framework.

Steps to reproduce:
Use` Cm_Cache_Backend_File::save` with no $specificLifetime (= false).
`Zend_Cache_Backend::getLifetime (Cm_Cache_Backend_File ~197)` returns null, but Update converts null to an int.
`Zend_Cache_Backend_File::_expireTime` returns $time() + 0, so lifetime is already expired.

In Version 1.4.5 the int Conversion is not there, so $`lifetime `is still null and `Zend_Cache_Backend_File::_expireTime` returns `9999999999 `which means unlimited lifetime.

There is no update von `Zend_Cache_Backend` with changend functionality so default functionality with this update to 1.4.6 were changed.

**Comment by colinmollenhour** [comment]
I will revert #35

**Comment by colinmollenhour** [comment]
Thanks for the report, fixed in [1.4.7](https://github.com/colinmollenhour/Cm_Cache_Backend_File/releases/tag/v1.4.7)

**Comment by pcs-matze** [comment]
Hi @colinmollenhour 
Thanks for fast new update, I've already checked and it works!
